### ISSUE TITLE
Allow the user to modify bag placement.

### ISSUE THREAD

**Issue by blindndangerous** [Duugu/Sku#106]
Right now, we have no way to add or modify bag placements.  As a hunter, I'd like to purchase better quivers, but can't equip them.
Purchase a bag from a merchant or in some other way.
Press B and go to container 1>the bag you just purchased.
Right clicking will just replace the bag in the old bag, and not do anything, and left clicking puts it on the cursor but no way to replace the old bags one menu to the left.

**Comment by Duugu** [comment]
Done
