### ISSUE TITLE
Question about cities in wow

### ISSUE THREAD

**Issue by sacralis666** [Duugu/Sku#221]
Hi ! I am not a blind person but we have a few blind folks in our guild. I was wondering if cities are mapped into SKU as we have this person constantly asking to escort them in Dalaran for exemple. Aren't cities included in the addon ? Great work btw ! I am glad more ppl are able to play wow !

**Comment by Duugu** [comment]
Hey. Yeah, everything is mapped. Including cities. Please feel free to join your discord or tell your guild members to get more information/ask questions: https://discord.gg/AzFwTDmpbk
