### ISSUE TITLE
Bags: pageup/down instead of double up/down for empty slots?

### ISSUE THREAD

**Issue by Duugu** [Duugu/Sku#55]

**Comment by SamKacer** [comment]
I was thinking of having feature when navigating through bag slots to have ctrl + down /up navigate to the next non-empty bag slot. Not sure if this is what is meant by this issue, but if so, then this feature would be greatly welcomed

**Comment by Duugu** [comment]
There already is such a feature. If you are on an empty bag slot, just press Down arrow twice fast, to get to the next non-empty slot.
This issue is just on enhancing that / to add an additional option.

**Comment by Duugu** [comment]
ctrl + down / up can't be used, as all combinations with control / shift and down/up are already used to show tooltips of menu items.
