### ISSUE TITLE
Mailbox Issue Sending Items to people I don't know.

### ISSUE THREAD

**Issue by Nils31011992** [Duugu/Sku#89]
If I want to send a Letter to someone that contains Items like gold or other Stuff, there sometimes pops up a Menu where I have to agree, that I really want to Send the Letter because I don't know the Person. This Menu is not Accessible with the Sku-Addon.

**Comment by Duugu** [comment]
nothing happens on sending a first aid manual

**Comment by Duugu** [comment]
items menu in send mail hasn't filtering enabled

**Comment by Duugu** [comment]
Filtering fixed with 20.1

**Comment by Duugu** [comment]
Sending items fixed with 20.1
